namespace Zhuomian.Spike.PlatformLifecycle;

internal sealed record PlatformLifecycleEvidence(
    int SchemaVersion,
    DateTimeOffset TimestampUtc,
    string OsVersion,
    string ProcessArchitecture,
    int MonitorCount,
    bool Passed,
    bool CoverageComplete,
    bool RealFullscreenTested,
    bool RealLockTested,
    bool RealUacSecureDesktopTested,
    bool FullscreenBecameForeground,
    bool FullscreenDetected,
    bool FullscreenClassifiedSuspended,
    int SuspendedHoverAttempts,
    int SuspendedHoverExpansions,
    bool RuntimeResourcesReleased,
    bool InputDesktopAccessible,
    string? InputDesktopName,
    bool InputDesktopWasDefault,
    bool SessionNotificationRegistered,
    bool SessionNotificationUnregistered,
    bool UnlockAloneStayedSuspended,
    bool DesktopReadyRequiredAccessibleDefault,
    bool SafeResumeState,
    bool ChildExited,
    bool OriginalForegroundRestored,
    bool PointerRestored,
    IReadOnlyDictionary<string, bool> Checks,
    IReadOnlyList<string> FailedChecks,
    IReadOnlyList<string> Limitations);
